apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vms.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Vm
    plural: vms
  scope: Namespaced
  additionalPrinterColumns:
  - name: vmname
    type: string
    JSONPath: .spec.vmname
  - name: vm_uuid
    type: number
    JSONPath: .status.vmId
  - name: cpuUtilization
    type: number
    JSONPath: .status.cpuUtilization
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        status:
          properties:
            cpuUtilization:
              type: integer
              minimum: 0
              maximum: 100
